sudo: false
language: python
python:
  - 3.6

env:
 - TOXENV=py27-d110
 - TOXENV=py27-d111

 - TOXENV=py36-d20

install:
  - pip install tox "coverage<4.0" python-coveralls>=2.5 coveralls>=0.5 codecov

script:
  - tox -e $TOXENV -- py.test tests -v --capture=no
      --cov=adminfilters --cov-report=xml --cov-config=tests/.coveragerc

before_success:
  - coverage erase

after_success:
  - coverage combine
  - codecov
